import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SiteHeader } from '@/components/siteHeader'
import Footer from '@/components/footer'

import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hosting Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
<<<<<<< HEAD
          {children}
          <Toaster />
=======
          <SiteHeader />
          {children}
          <Footer />
>>>>>>> be8d09698f7c46b805005d946a509057cb29e2fe
        </ThemeProvider>
      </body>
    </html>
  )
}
